apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: http-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http-port
          containerPort: 80
      volumeMounts:
        - name: documentroot
          mountPath: /usr/share/nginx/html
  volumes:
    - name: documentroot
      hostPath:
        path: /PATH/TO/DIR # 作業ディレクトリ
